behaviors:
    CarDrive:
        trainer_type: ppo

        max_steps: 3.0e7
        time_horizon: 64
        summary_freq: 30000
        keep_checkpoints: 5

        hyperparameters:
            batch_size: 1024
            buffer_size: 81920
            learning_rate: 3.0e-4
            #beta: 5.0e-3
            beta: 1.0e-4
            #buffer_size: 10240
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear

        network_settings:
            #normalize: false
            normalize: true
            #hidden_units: 128
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
            # memory:
            #     memory_size: 128
            #     sequence_length: 64
        #use_recurrent: false

        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99